// Generated by UE_Test/scripts/terrain_v2/export_layout.py (terrain v2) - do not edit by hand. Godot frame: x east, z south, metres.
#pragma once

#include "CoreMinimal.h"

namespace OsrWorld
{
	inline const FVector Carrier(-32769.8, 0.0, 15157.4);
	inline const FVector Mouth(-20915.7, 0.0, 11191.2);
	inline const FVector Target(11500.0, 833.9, -2600.0);
}
