# Terrain v2 gameplay layout: canyon path for the -autotest autopilot (Content/Data/canyon_path.txt, Godot frame "x y z" every 200 m,
# y = floor height or 0 on water, from the open sea through the fjord centreline and up the trunk river to the target) and the
# generated C++ header Source/SilentRidgeUE/OsrWorldLayout.h (carrier, fjord mouth, target).
import heapq, os
import numpy as np
from scipy import ndimage
from scipy.interpolate import splprep, splev
import tv2
from tv2 import X0

W = tv2.load("world_4096")
h = np.load(os.path.join(tv2.WORK, "h_global_final.npy"))
n = h.shape[0]; cell = tv2.MAP / n
route = W["route"][::-1]                                            # sea end first
TARGET = np.array([11500.0, -2600.0])

# ---- through the fjord to the open sea: cheapest water path, cost favours the middle of the fjord
k = 4; hc = h[::k, ::k]; cc = cell * k                               # 78 m grid
water = hc < 0.0
dsh = ndimage.distance_transform_edt(water) * cc
cost = np.where(water, 1.0 / np.maximum(dsh, 20.0) + 1e-4, np.inf)
start = tuple(np.clip(((route[0, 1] - X0) / cc, (route[0, 0] - X0) / cc), 0, hc.shape[0] - 1).astype(int))
if not water[start]:
    ys, xs = np.nonzero(water[start[0] - 20:start[0] + 20, start[1] - 20:start[1] + 20])
    d = (ys - 20) ** 2 + (xs - 20) ** 2
    start = (start[0] - 20 + ys[d.argmin()], start[1] - 20 + xs[d.argmin()])
goal_mask = water & (dsh > 2500.0)                                   # open water
dist = np.full(hc.shape, np.inf); prev = {}
dist[start] = 0.0; pq = [(0.0, start)]; goal = None
while pq:
    dcur, (y, x) = heapq.heappop(pq)
    if dcur > dist[y, x]:
        continue
    if goal_mask[y, x]:
        goal = (y, x); break
    for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)):
        yy, xx = y + dy, x + dx
        if 0 <= yy < hc.shape[0] and 0 <= xx < hc.shape[1] and water[yy, xx]:
            nd = dcur + cost[yy, xx] * (1.414 if dy and dx else 1.0)
            if nd < dist[yy, xx]:
                dist[yy, xx] = nd; prev[(yy, xx)] = (y, x); heapq.heappush(pq, (nd, (yy, xx)))
sea = [goal]
while sea[-1] != start:
    sea.append(prev[sea[-1]])
sea = np.array([[X0 + x * cc, X0 + y * cc] for y, x in sea])        # open sea -> fjord head
full = np.concatenate([sea, route[1:]])
# ---- smooth + resample every 200 m
_, keep = np.unique(np.round(full / 5.0), axis=0, return_index=True)
full = full[np.sort(keep)]
tck, u = splprep([full[:, 0], full[:, 1]], s=len(full) * float(os.environ.get('PATH_SMOOTH', '3000')))
fine = np.array(splev(np.linspace(0, 1, 20000), tck)).T
arc = np.r_[0, np.cumsum(np.linalg.norm(np.diff(fine, axis=0), axis=1))]
s = np.arange(0, arc[-1], 200.0)
P = np.stack([np.interp(s, arc, fine[:, 0]), np.interp(s, arc, fine[:, 1])], 1)
floor = np.maximum(tv2.sample_world(h, cell, P[:, 0], P[:, 1]), 0.0)
out = os.path.join(tv2.ROOT, "UE_Test", "SilentRidgeUE", "Content", "Data", "canyon_path.txt")
with open(out, "w") as f:
    for (x, z), y in zip(P, floor):
        f.write("%.1f %.1f %.1f\n" % (x, y, z))
dry = int(np.argmax(floor > 5.0))
dshg = ndimage.distance_transform_edt(h < 0) * cell
sh = tv2.sample_world(dshg, cell, P[:, 0], P[:, 1])
mouth_i = int(np.argmax(sh < 1300.0))
MOUTH = P[mouth_i]
# carrier: 12 km out to sea from the mouth along the fjord axis, ~40-50 km from the target
axis = P[max(mouth_i - 1, 0)] - P[min(mouth_i + 15, len(P) - 1)]; axis /= np.linalg.norm(axis)
CARRIER = MOUTH + axis * 12500.0
print("path %d pts, %.1f km (%.1f km water, dry from pt %d); mouth (%.0f, %.0f); carrier (%.0f, %.0f) depth %.0f m; carrier-target %.1f km"
      % (len(P), s[-1] / 1000, s[dry] / 1000, dry, MOUTH[0], MOUTH[1], CARRIER[0], CARRIER[1], tv2.sample_world(h, cell, *CARRIER)[0],
         np.linalg.norm(CARRIER - TARGET) / 1000))
# curvature check (flyability): radius of the smoothed centreline
d1 = np.gradient(P, axis=0); d2 = np.gradient(d1, axis=0)
curv = np.abs(d1[:, 0] * d2[:, 1] - d1[:, 1] * d2[:, 0]) / np.maximum(np.linalg.norm(d1, axis=1) ** 3, 1e-9)
print("min turn radius on the dry canyon: %.0f m (p5 %.0f m)" % (1.0 / max(curv[dry:].max(), 1e-9), np.percentile(1.0 / np.maximum(curv[dry:], 1e-9), 5)))
# does the smoothed line stay over the valley floor? height above the river floor nearest to each point
from scipy.spatial import cKDTree
rf = W["route_floor"][::-1]; rr = route
_, ii = cKDTree(rr).query(P)
above = floor - np.maximum(rf[ii], 0)
print("smoothed path height above river floor: p50 %.0f p95 %.0f max %.0f m" % (np.median(above[dry:]), np.percentile(above[dry:], 95), above[dry:].max()))
hdr = os.path.join(tv2.ROOT, "UE_Test", "SilentRidgeUE", "Source", "SilentRidgeUE", "OsrWorldLayout.h")
with open(hdr, "w") as f:
    f.write("// Generated by UE_Test/scripts/terrain_v2/export_layout.py (terrain v2) - do not edit by hand. Godot frame: x east, z south, metres.\n")
    f.write("#pragma once\n\n#include \"CoreMinimal.h\"\n\nnamespace OsrWorld\n{\n")
    f.write("\tinline const FVector Carrier(%.1f, 0.0, %.1f);\n" % (CARRIER[0], CARRIER[1]))
    f.write("\tinline const FVector Mouth(%.1f, 0.0, %.1f);\n" % (MOUTH[0], MOUTH[1]))
    f.write("\tinline const FVector Target(%.1f, %.1f, %.1f);\n" % (TARGET[0], float(tv2.sample_world(h, cell, *TARGET)[0]), TARGET[1]))
    f.write("}\n")
np.save(os.path.join(tv2.WORK, "canyon_path.npy"), np.c_[P, floor])
print("wrote", out, hdr)
